"use client";

import { FormEvent, useEffect, useState } from "react";

type Settings = { fullReportPriceEgp: string; vodafoneCashNumber: string; vodafoneDeepLink: string; vodafoneEnabled: boolean; orangeCashNumber: string; orangeEnabled: boolean; instapayIdentifier: string; instapayEnabled: boolean; paymentInstructions: string; supportContact: string; freeRecommendationCount: number; homepageStageMessage: string };

export function AdminSettingsForm() {
  const [settings, setSettings] = useState<Settings | null>(null);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);
  useEffect(() => { void fetch("/api/admin/settings").then(async (response) => { if (response.ok) setSettings((await response.json()).settings); }); }, []);
  if (!settings) return <p className="text-sm text-slate-500">جارٍ تحميل إعدادات الدفع…</p>;
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setMessage(""); const data = new FormData(event.currentTarget);
    const payload = { fullReportPriceEgp: Number(data.get("fullReportPriceEgp")), vodafoneCashNumber: data.get("vodafoneCashNumber"), vodafoneDeepLink: data.get("vodafoneDeepLink"), vodafoneEnabled: data.get("vodafoneEnabled") === "on", orangeCashNumber: data.get("orangeCashNumber"), orangeEnabled: data.get("orangeEnabled") === "on", instapayIdentifier: data.get("instapayIdentifier"), instapayEnabled: data.get("instapayEnabled") === "on", paymentInstructions: data.get("paymentInstructions"), supportContact: data.get("supportContact"), freeRecommendationCount: Number(data.get("freeRecommendationCount")), homepageStageMessage: data.get("homepageStageMessage") };
    const response = await fetch("/api/admin/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
    const result = await response.json(); setMessage(response.ok ? "تم حفظ الإعدادات وتسجيل التغيير." : result.error); if (response.ok) setSettings(result.settings); setLoading(false);
  }
  return <form onSubmit={submit} className="mt-4 grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm font-bold">السعر بالجنيه<input name="fullReportPriceEgp" type="number" step="0.01" defaultValue={settings.fullReportPriceEgp} className="min-h-10 border border-slate-300 px-3" /></label><label className="grid gap-1 text-sm font-bold">عدد التوصيات المجانية<input name="freeRecommendationCount" type="number" min="1" max="10" defaultValue={settings.freeRecommendationCount} className="min-h-10 border border-slate-300 px-3" /></label><label className="grid gap-1 text-sm font-bold">فودافون كاش<input name="vodafoneCashNumber" defaultValue={settings.vodafoneCashNumber} className="min-h-10 border border-slate-300 px-3" /><span><input name="vodafoneEnabled" type="checkbox" defaultChecked={settings.vodafoneEnabled} /> مفعّل</span></label><label className="grid gap-1 text-sm font-bold">رابط فودافون<input name="vodafoneDeepLink" defaultValue={settings.vodafoneDeepLink} className="min-h-10 border border-slate-300 px-3 ltr-number" /></label><label className="grid gap-1 text-sm font-bold">أورنج كاش<input name="orangeCashNumber" defaultValue={settings.orangeCashNumber} className="min-h-10 border border-slate-300 px-3" /><span><input name="orangeEnabled" type="checkbox" defaultChecked={settings.orangeEnabled} /> مفعّل</span></label><label className="grid gap-1 text-sm font-bold">إنستا باي<input name="instapayIdentifier" defaultValue={settings.instapayIdentifier} className="min-h-10 border border-slate-300 px-3" /><span><input name="instapayEnabled" type="checkbox" defaultChecked={settings.instapayEnabled} /> مفعّل</span></label><label className="grid gap-1 text-sm font-bold md:col-span-2">تعليمات الدفع<textarea name="paymentInstructions" defaultValue={settings.paymentInstructions} className="min-h-20 border border-slate-300 p-3" /></label><label className="grid gap-1 text-sm font-bold">دعم WhatsApp<input name="supportContact" defaultValue={settings.supportContact} className="min-h-10 border border-slate-300 px-3" /></label><label className="grid gap-1 text-sm font-bold">رسالة المرحلة<input name="homepageStageMessage" defaultValue={settings.homepageStageMessage} className="min-h-10 border border-slate-300 px-3" /></label><div className="md:col-span-2"><button disabled={loading} className="min-h-11 bg-teal-700 px-5 font-bold text-white">حفظ إعدادات التشغيل</button>{message ? <span className="mr-3 text-sm font-bold text-teal-800">{message}</span> : null}</div></form>;
}
